{% set name = "hopfield4py" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hopfield4py-{{ version }}.tar.gz
  sha256: 4d58e534ff849db321dd4075b8a6988cb9eadd5470c636f4d9e31645f638d22e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - tensorflow

test:
  imports:
    - hopfield4py
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://bitbucket.org/fvalle01/hopfield4py
  summary: Package to run Hopfield model.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fvalle1
